### ISSUE TITLE
Getting build errord

### ISSUE THREAD

**Issue by mwoodpatrick** [second-state/ssvm-deno-starter#1]
I pulled this code but am getting a bunch of build errors. In the code I have and that I see in the tree I don't see the definitions for these functions, am I missing something?

Check file:///home/mwoodpatrick/projects/git/deno/ssvm-deno-starter/deno/server.ts
error: TS2339 [ERROR]: Property 'fdatasyncSync' does not exist on type 'typeof Deno'.
          Deno.fdatasyncSync(entry.handle.rid);
               ~~~~~~~~~~~~~
    at https://deno.land/std@0.63.0/wasi/snapshot_preview1.ts:501:16

TS2551 [ERROR]: Property 'fstatSync' does not exist on type 'typeof Deno'. Did you mean 'lstatSync'?
          const info = Deno.fstatSync(entry.handle.rid);
                            ~~~~~~~~~
    at https://deno.land/std@0.63.0/wasi/snapshot_preview1.ts:545:29

    'lstatSync' is declared here.
      export function lstatSync(path: string | URL): FileInfo;
                      ~~~~~~~~~
        at asset:///lib.deno.ns.d.ts:1485:19

TS2551 [ERROR]: Property 'ftruncateSync' does not exist on type 'typeof Deno'. Did you mean 'truncateSync'?
          Deno.ftruncateSync(entry.handle.rid, Number(size));
               ~~~~~~~~~~~~~
    at https://deno.land/std@0.63.0/wasi/snapshot_preview1.ts:616:16

    'truncateSync' is declared here.
      export function truncateSync(name: string, len?: number): void;
                      ~~~~~~~~~~~~
        at asset:///lib.deno.ns.d.ts:1611:19

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
          Deno.utimeSync(entry.path, Number(atim), Number(mtim));
               ~~~~~~~~~
    at https://deno.land/std@0.63.0/wasi/snapshot_preview1.ts:648:16

TS2339 [ERROR]: Property 'fsyncSync' does not exist on type 'typeof Deno'.
          Deno.fsyncSync(entry.handle.rid);
               ~~~~~~~~~
    at https://deno.land/std@0.63.0/wasi/snapshot_preview1.ts:914:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
          Deno.utimeSync(path, Number(atim), Number(mtim));
               ~~~~~~~~~
    at https://deno.land/std@0.63.0/wasi/snapshot_preview1.ts:1117:16

TS2339 [ERROR]: Property 'linkSync' does not exist on type 'typeof Deno'. 'Deno.linkSync' is an unstable API. Did you forget to run with the '--unstable' flag?
          Deno.linkSync(old_path, new_path);
               ~~~~~~~~
    at https://deno.land/std@0.63.0/wasi/snapshot_preview1.ts:1159:16

TS2339 [ERROR]: Property 'symlinkSync' does not exist on type 'typeof Deno'. 'Deno.symlinkSync' is an unstable API. Did you forget to run with the '--unstable' flag?
          Deno.symlinkSync(old_path, new_path);
               ~~~~~~~~~~~
    at https://deno.land/std@0.63.0/wasi/snapshot_preview1.ts:1435:16

Found 8 errors.

**Comment by mwoodpatrick** [comment]
Looks like issue was version mismatch 

diff --git a/deno/server.ts b/deno/server.ts
index 3ef626f..2768f99 100644
--- a/deno/server.ts
+++ b/deno/server.ts
@@ -1,4 +1,4 @@
-import { serve } from "https://deno.land/std@0.61.0/http/server.ts";
+import { serve } from "https://deno.land/std@v0.63.0/http/server.ts";
 import { say } from '../pkg/functions_lib.js';

 type Resp = {

Also need additional flags to run, need:

deno run --unstable --allow-env --allow-read --allow-net deno/server.ts
